[package]
name = "rux"
version = "0.1.0"
authors = ["Wei Tang <hi@beyond.codes>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
spin = "0.3.4"
bitflags = { version = "0.4", features = ["no_std"] }
x86 = { version = "0.6.0", default-features = false }
